name: widget_to_image
description: A simple package to convert any of your widgets into an image.
homepage: https://github.com/nbrucker/widget_to_image

version: 1.0.5

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  lint: ^2.3.0

flutter:
